-- Calculate the total amount paid by each customer. Display the customer_id, first_name, last_name, and the total amount paid, and sort the results alphabetically by the last_name and then by the first_name.
-- Write Query Here
